version: '3.8'
services:
  db:
    image: commoncontainersregistry.azurecr.io/common-db:1.0.0
    container_name: common-db
    domainname: "common-app"
#    ports:
#      - "3306:3306"

  web:
    container_name: common-web
    image: commoncontainersregistry.azurecr.io/common-web:1.0.0
    restart: always
    domainname: "common-app"
#    ports:
#      - "8080:8080"

  ui:
    container_name: common-ui
    image: commoncontainersregistry.azurecr.io/common-ui:1.0.0
    restart: always
    domainname: "common-app"
    ports:
      - "80:80"
